---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%L%z
      tag kube.*
      <parse>
        @type json
        time_key time
        keep_time_key true
      </parse>
    </source>

    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    <match kube.**>
      @type elasticsearch
      @id elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME']}"
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y%m%d
      include_tag_key true
      type_name _doc
      buffer_path /var/log/fluentd-buffers/
      flush_interval 5s
      max_retry_wait 30s
      disable_retry_limit
      num_threads 2
      reload_connections true
      request_timeout 300s  # Set to 5 minutes (300 seconds)
      reconnect_on_error true
      reload_on_failure true
      log_es_400_reason true
    </match>
