kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      group_by: [cluster]
      # If an alert isn't caught by a route, send it slack.
      receiver: slack-all
      routes:
        - match:
            severity: slack
          receiver: slack-all


    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '#sock-shop'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: 'https://hooks.slack.com/services/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'
