apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      initContainers:
        - name: init-config
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Copying and replacing API_URL_SECRET with actual Slack URL."
              cp /etc/alertmanager/config.yml /config/config.yml && \
              sed -i "s|API_URL_SECRET|${SLACK_HOOK_URL}|g" /config/config.yml
          env:
            - name: SLACK_HOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-hook-url
                  key: SLACK_HOOK_URL
          volumeMounts:
            - name: config-volume
              mountPath: /config
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          command:
            - "/bin/alertmanager"
          args:
            - "--config.file=/etc/alertmanager/config.yml"
          ports:
            - name: alertmanager
              containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager/config.yml
              subPath: config.yml
      volumes:
        - name: config-volume
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
