apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Replacing API_URL_SECRET with actual Slack URL."
          sed "s|API_URL_SECRET|${SLACK_HOOK_URL}|g" /etc/alertmanager/config.yml > /etc/alertmanager/config.tmp
          mv /etc/alertmanager/config.tmp /etc/alertmanager/config.yml
        env:
          - name: SLACK_HOOK_URL
            valueFrom:
              secretKeyRef:
                name: slack-hook-url
                key: SLACK_HOOK_URL
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager/config.yml
          subPath: config.yml
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      nodeSelector:
        kubernetes.io/os: linux
